In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/play_tennis.csv')

In [3]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
#creating the lookup table for the desired probability

In [5]:
#probability of yes and no

data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py = 9/14

In [7]:
pn = 5/14

In [8]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [9]:
#for the outlook column
pd.crosstab(data['outlook'] , data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [11]:
#temp

pd.crosstab(data['temp'] , data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
PCoolNo = 1/5
PHotNo = 2/5
PMildNo = 2/5

PCoolYes = 3/9
PHotYes = 2/9
PMildYes = 4/9

In [13]:
#Humidity
pd.crosstab(data['humidity'] , data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [14]:
PHighNo   = 4/5
PNormalNo = 1/5

PHighYes = 3/9
PNormalYes = 6/9

In [15]:
#wind
pd.crosstab(data['wind'] , data['play'])
#

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [16]:
pstrongNo = 3/5
PweakNo = 2/5
PStrongYes = 3/9
PWeakYes = 6/9

In [18]:
#outlook = sunny , temp = Hot , humidity = high , wind = weak

Pyes = py*Psy*PHotYes*PHighYes*PWeakYes

In [19]:
Pyes

0.007054673721340388

In [21]:
Pno = pn*Psn*PHighNo*PHotNo*PweakNo

In [22]:
Pno

0.02742857142857143

In [ ]:
#No Play